# Generated by Django 3.2 on 2022-05-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220508_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accounts',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
