# Generated by Django 3.2 on 2022-05-08 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_id_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invest_combination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weights', models.FloatField()),
                ('shares', models.FloatField()),
                ('combination_id', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ROI', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='Member_invest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('combination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.invest_combination')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
    ]
