# Generated by Django 3.2 on 2022-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_company_invest_combination_member_invest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
